# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print("Size of the array: ",
      x.size)
  
print("Memory size of one array element in bytes: ",
      x.itemsize)
  
# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

Size of the array:  10
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# to check info in py editor
print(np.info(np.add))

# to check info in CMD
#python -c import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
x = np.zeros(10)
print(x)
x[4] = 1
print(x)

#or
y  = (np.arange(10) == 4).astype(int)
print(y)

#or
z = (np.arange(10) == 4).view(np.uint8)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
x = np.arange(10, 50)
print(x)
rev_x = x[::-1]

print(rev_x)
#x.reverse()


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
a =  np.arange(0, 9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
arr = np.array([1,2,0,0,4,0])
non_zero_arr = np.nonzero(arr)
print(arr)
print(non_zero_arr)

[1 2 0 0 4 0]
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
ar = np.identity(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
Arr = np.random.random((3,3,3))
print(Arr)

[[[0.12284427 0.06546803 0.14001761]
  [0.67804872 0.85507294 0.35513215]
  [0.59400007 0.06336683 0.76334843]]

 [[0.19576538 0.92921491 0.24662248]
  [0.18640739 0.91968749 0.14153811]
  [0.66244783 0.76543355 0.93315951]]

 [[0.62034811 0.89703946 0.76448998]
  [0.34098697 0.75060204 0.10840391]
  [0.36548507 0.94178249 0.03692576]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Arr_10_10 = np.random.random((10,10))
print(Arr_10_10)

[[0.03345225 0.65302785 0.80584772 0.67777957 0.26912153 0.50101657
  0.29876163 0.84280133 0.96141056 0.61749134]
 [0.85360186 0.287403   0.38580535 0.86016487 0.97836483 0.48784628
  0.83901063 0.00815599 0.39940101 0.33299958]
 [0.53522771 0.00211979 0.29055336 0.5112361  0.64937131 0.55892336
  0.61682157 0.29434306 0.31548763 0.18574246]
 [0.55382693 0.082392   0.96313149 0.89573823 0.67622674 0.8629831
  0.92706948 0.70587319 0.44874999 0.63399505]
 [0.23792286 0.85979686 0.957295   0.18218609 0.44758921 0.20897051
  0.09457953 0.5884713  0.19211461 0.04045287]
 [0.58865617 0.98084855 0.50854172 0.98809156 0.42817579 0.21919816
  0.25459723 0.24590507 0.92501402 0.02821479]
 [0.2753562  0.49069294 0.61190085 0.3746876  0.52428537 0.44408985
  0.32486428 0.34896025 0.57444669 0.70618453]
 [0.82045706 0.0562611  0.42677873 0.03220637 0.83676577 0.02479228
  0.71173885 0.62849538 0.8491785  0.82246866]
 [0.01413028 0.09840087 0.3692323  0.00954266 0.88838593 0.48792364
  0.48962308 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
arr_30 = x = np.random.random(30)
print(arr_30)
print("mean =", arr_30.mean())

[0.36818472 0.11446632 0.34001149 0.42009738 0.32412504 0.79846597
 0.35256819 0.60898317 0.61084762 0.93824922 0.2518762  0.17298249
 0.25610895 0.20161273 0.66606375 0.67689531 0.3066435  0.12571535
 0.68558472 0.31277732 0.24277098 0.73253181 0.33704734 0.56086242
 0.30381571 0.83746532 0.31432879 0.49630788 0.48710136 0.98341581]
mean = 0.46093022852319987


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
x = np.ones((4,4))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
x = np.ones((4,4))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
z = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(z)

Original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
x = np.diag([1, 2, 3, 4, 5],(-1))
print(x)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
#x = np.ones((8,8))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
#arr = np.zeros((6,7,8))
#print(arr)
#index = list.index(100)
index = np.unravel_index(100,(6,7,8))
print(index)
# to check the element position 
element = np.ravel_multi_index((1,5,4), (6,7,8))
print(element)

(1, 5, 4)
100


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
# to print checkerboard with tile fun
x = np.array([[0,1],[1,0]])
print(x)
x_tile = np.tile(x,(4,4))
print(f'Tile matrix: \n {x_tile}')

#or can do it in one line
z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(f'z: {z}')
#def printcheckboard(n):
#final = []
#n = 8
#for i in range(4*4):
#    final.append(list(np.tile([0,1],int(n/2))) if i%2==0 else list(np.tile([1,0],int(n/2))))
#print(np.array(final))

#printcheckboard(n)

[[0 1]
 [1 0]]
Tile matrix: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
z: [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
x = np.random.rand(5*5)
print(x)
normalized_x= x/np.linalg.norm(x)
print(normalized_x)

[0.00256472 0.25140922 0.57637474 0.29234049 0.63897759 0.62273333
 0.37767569 0.55464962 0.24919816 0.61377042 0.560766   0.03634811
 0.04693922 0.37076844 0.24722069 0.22853039 0.77814568 0.64223302
 0.67616444 0.42048103 0.51527586 0.66218167 0.30858215 0.00829459
 0.10266133]
[0.00112506 0.11028566 0.25283826 0.12824098 0.28030024 0.27317437
 0.16567496 0.2433081  0.10931574 0.26924262 0.24599117 0.01594482
 0.02059082 0.16264496 0.10844828 0.10024941 0.3413491  0.2817283
 0.296613   0.18445237 0.22603602 0.29047917 0.13536571 0.00363859
 0.04503444]


In [23]:
m= np.random.random((5,5))
print("Original Array:")
print(m)
xmax, xmin = x.max(), x.min()
m_norml = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(m_norml)


Original Array:
[[0.33095487 0.30189064 0.17611802 0.11588724 0.25683829]
 [0.48332038 0.85823387 0.9070969  0.13306462 0.50372637]
 [0.13063873 0.63375126 0.61841631 0.79989743 0.95554582]
 [0.59663701 0.82811457 0.06768068 0.79668288 0.07186439]
 [0.66766304 0.90457128 0.73810297 0.97627709 0.5231212 ]]
After normalization:
[0.         0.32084917 0.73984542 0.37362414 0.82056278 0.79961815
 0.48365159 0.71183401 0.31799832 0.78806177 0.7197202  0.04355882
 0.05721453 0.47474569 0.31544866 0.29135021 1.         0.8247602
 0.86850988 0.53884292 0.66106721 0.8504811  0.39456543 0.00738785
 0.12906018]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\himan\AppData\Local\Temp\ipykernel_13288\295437610.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
f_mul = np.dot(np.ones((5,3)), np.ones((3,2)))
print(f_mul)

#other way
x1 = np.arange(15).reshape((5, 3))
print(x1)
y1= np.arange(6).reshape((3, 2))
print(y1)
np.dot(x1, y1)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
arre = np.arange(10)
print(arre)
arre[(3 < arre) & (arre < 8)] *= -1
print("after negate:", arre)

#or
arr = np.arange(10)
arr[3:9] = np.multiply(arr[3:9],-1)
print("after negate:", arre)


[0 1 2 3 4 5 6 7 8 9]
after negate: [ 0  1  2  3 -4 -5 -6 -7  8  9]
after negate: [ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1)) #= 9
from numpy import *
print(sum(range(5),-1))  #=10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
#Bit Shift
# Syntax
#left shift =  some_int << number_of_bits
#x<<n == x*(2^n)

#right shift = some_int >> number_of_bits
# x>>n == x/(2^n)

In [29]:
Z = np.arange(4)
print(Z)
print(Z ** Z)      # = [0^0, 1^1, 2^2, 3^3] = [1, 1, 4, 27]
print(2 << Z >> 2)  # = [0, 1, 2, 4]
print(Z < - Z )     # = [False, False, False, False]
print(1j * Z)       # = [0 + 0.j, 0 + 1.j, 0 + 2.j, 0 + 3j]
print(Z / 1 / 1)    # = [0, 1, 2,3]
print(Z < Z > Z )   # ValueError

[0 1 2 3]
[ 1  1  4 27]
[0 1 2 4]
[False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j]
[0. 1. 2. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\himan\AppData\Local\Temp\ipykernel_15248\548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\himan\AppData\Local\Temp\ipykernel_15248\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Y = np.random.uniform(-5,+5,5)
print(Y)
print (np.copysign(np.ceil(np.abs(Y)), Y))

[ 3.2132053  -4.57988532  1.37631033  3.30176318  1.41074644]
[ 4. -5.  2.  4.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
print(Z1)
Z2 = np.random.randint(0,5,5)
print(Z2)
print("common values b/w Z1 & Z2:" ,np.intersect1d(Z1,Z2))

[4 8 5 2 5 9 8 8 8 0]
[3 1 2 4 2]
common values b/w Z1 & Z2: [2 4]
